### ISSUE TITLE
Application doen't start on macOS 10.12.4

### ISSUE THREAD

**Issue by MirstrKot** [rjoudrey/swift-init-generator#3]
It worked one month ago, but after mac os update it doesn't start.

I tried to install new version swift init generator - same issue.

I did:
```
Download the app extension
Unzip it
Move Swift Initializer Generator.app to Applications
```
`Start Swift Initializer Generator.app ` doesn't work

Error message is "Application quit unexpectedly"
[error screenshot](https://monosnap.com/file/mmeJMwLQCgtOuD8mMX2ZXXZBnHfZJH)

macOS 10.12.4

**Comment by Robuske** [comment]
Same problem

**Comment by Robuske** [comment]
Doing the alternate installation works though

**Comment by ga-tungnguyen** [comment]
Same problem

**Comment by rjoudrey** [comment]
It would be helpful if you could attach the relevant crash log from ~/Library/Logs/DiagnosticReports/.
I think it's caused by the deployment target setting of the target being higher than the version of macOS you are running. It might suffice for me to lower the setting to lower macOS version and re-build it.

**Comment by Sroka** [comment]
Same problem

Process:               Swift Initializer Generator [23273]
Path:                  /Applications/Swift Initializer Generator.app/Contents/MacOS/Swift Initializer Generator
Identifier:            rjoudrey.SwiftInitializerGenerator
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Swift Initializer Generator [23273]
User ID:               504

Date/Time:             2018-02-09 12:52:12.737 +0100
OS Version:            Mac OS X 10.12.6 (16G1212)
Report Version:        12
Anonymous UUID:        A17227D2-3E2E-95C0-FDD0-F68DDD1B737F


Time Awake Since Boot: 15000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 0000000108b06000-000000010a6a9000 [ 27.6M] r-x/rwx SM=COW  @:a [(null)]

Thread 0 Crashed:
0   d,a                          	0x0000000119f7d000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007fff570f9b70
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x0000000119f7d000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0


Binary Images:
       0x108b06000 -        0x10a6a8fff +d,a (0) <6D38A5AE-6CB8-3829-B081-072248153C69> d,a
       0x119f7c000 -        0x119fb9dc7 +d,a (433.5) <93EA668C-4BB2-3646-96E9-B406B81308D6> d,a

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 10520
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=34.5M resident=0K(0%) swapped_out_or_unallocated=34.5M(100%)
Writable regions: Total=8472K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8472K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        2 
Stack                             8192K        2 
__DATA                            1336K        5 
__LINKEDIT                        6748K        3 
__TEXT                            27.9M        3 
shared memory                        8K        3 
===========                     =======  ======= 
TOTAL                             99.8M       12 

Model: iMac14,2, BootROM IM142.0123.B00, 4 processors, Intel Core i5, 3,4 GHz, 16 GB, SMC 2.15f7
Graphics: NVIDIA GeForce GTX 775M, NVIDIA GeForce GTX 775M, PCIe, 2048 MB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x111), Broadcom BCM43xx 1.0 (7.21.171.133.1a2)
Bluetooth: Version 5.0.5f1, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Network Service: iPad, Ethernet, en6
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: APPLE SSD SM0512F, 500,28 GB
USB Device: USB 3.0 Bus
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: FaceTime HD Camera (Built-in)
USB Device: HP USB Optical Mouse
USB Device: iPad
Thunderbolt Bus: iMac, Apple Inc., 23.10

**Comment by crperezt** [comment]
Any plans of getting this fixed?

**Comment by rjoudrey** [comment]
I no longer have an active developer program subscription, meaning that the certificate has probably been revoked. The only thing I can recommend is using the alternate installation.

**Comment by rjoudrey** [comment]
I updated the recommended installation method a while back and haven't heard any complaints since. Closing this.
